//AUTH Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

////USER////
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_API_TOKEN = 'SET_API_TOKEN';
export const SET_NOTIFY = 'SET_NOTIFY';
export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';
export const SET_INTERNET = 'SET_INTERNET';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_LOCATION_STATUS = 'SET_LOCATION_STATUS';
export const SET_IN_APP_NOTIFICATION = 'SET_IN_APP_NOTIFICATION';
export const LOGOUT_LOADER = 'LOGOUT_LOADER';
export const SET_IS_MEMBERSHIP_ACTIVE = 'SET_IS_MEMBERSHIP_ACTIVE';

///FILTERS///

export const SET_CARLIST_FILTERS = 'SET_CARLIST_FILTERS';
export const SET_MY_VEHICLES_LIST_FILTERS = 'SET_MY_VEHICLES_LIST_FILTERS';
export const SET_MY_VEHICLES_LIST_FILTERS_DEALER = 'SET_MY_VEHICLES_LIST_FILTERS_DEALER';
export const SET_USER_LIST_FILTERS = 'SET_USER_LIST_FILTERS';
